select distinct OBJECT_OWNER,OBJECT_NAME from v$sql_plan
where operation = 'INDEX' and OBJECT_OWNER not in (
'SYSTEM','SYS','DBSNMP','SYSMAN','TEST','XIAOHUANG','SCOTT','XIAOBAI','CHINA_CLP','CHINA_CLP_READ','CHINA_CLP_APP','MGMT_VIEW','OUTLN','OLAPSYS',
'SI_INFORMTN_SCHEMA','OWBSYS','ORDPLUGINS','XDB','ANONYMOUS','CTXSYS','ORDDATA','OWBSYS_AUDIT','APEX_030200',
'APPQOSSYS','WMSYS','EXFSYS','ORDSYS')
